fix(PT-12973): Fixed log file flooding with continue on error enabled
shopware5/SwagImportExport pull request #58
Opened 2023-07-20 09:09 UTC by rathmerdominik

2023-07-24 07:43 UTC, swDennis approved these changes

2023-07-24 13:22 UTC, ennasus4sun requested changes

2023-07-26 07:54 UTC, rathmerdominik commented on Tests/Functional/Components/Service/Mock/FileIoMockWithBrokenRecords.php
> +        // DO NOTHINGTe
It is indeed not :smile: will remove

2023-07-26 08:01 UTC, PascalThesing approved these changes

2023-07-26 11:21 UTC, ennasus4sun approved these changes

2023-07-26 11:21 UTC, merged

2023-07-27 08:11 UTC, mitelg commented
@rathmerdominik Changelog entry is missing.